version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
  web:
    image: powered/backend:latest
    volumes:
      - ./initialize.sh:/initialize.sh
    command: sh initialize.sh
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db

