# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-27 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('orders', '0002_auto_20181127_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('was_counter_offer', models.BooleanField()),
                ('is_final_fee', models.BooleanField(default=False)),
                ('offer_made_time', models.DateTimeField(auto_now_add=True)),
                ('offer_accept_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_fee',
            new_name='initial_delivery_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='acceptance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='final_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderfeeaction',
            name='for_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='orderfeeaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
        ),
    ]
